### ISSUE TITLE
Orthographe search-familly

### ISSUE THREAD

**Issue by arnaudpant** [Caro-L-dev/lingi-club#65]
Remplacer:
Vous regardez les familles parlent: Anglais par 
Vous regardez les familles qui parlent: Anglais
dans la page search-familly

**Comment by arnaudpant** [comment]
<img width="718" alt="Capture d’écran 2024-08-13 à 20 41 49" src="https://github.com/user-attachments/assets/6a65e587-afa0-4969-ba97-6c56de77d006">

**Comment by Aurelia77** [comment]
Corrigé sur ma branche feature/addingStudentRegistrationAndAccount
